# Generated by Django 4.2.30 on 2026-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RackDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_reference', models.CharField(blank=True, max_length=100)),
                ('site_name', models.CharField(max_length=150)),
                ('rack_name', models.CharField(max_length=150)),
                ('engineer', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('rack_capacity_u', models.PositiveIntegerField()),
                ('used_rack_u', models.PositiveIntegerField()),
                ('dc_voltage_v', models.FloatField()),
                ('ac_voltage_v', models.FloatField()),
                ('total_power_kw', models.FloatField()),
                ('installed_devices', models.PositiveIntegerField()),
                ('protected_circuits', models.PositiveIntegerField()),
                ('result_status', models.CharField(max_length=20)),
                ('result_message', models.TextField(blank=True)),
                ('devices', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
