# Generated by Django 4.2.30 on 2026-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CableSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_reference', models.CharField(blank=True, max_length=100)),
                ('site_name', models.CharField(max_length=150)),
                ('rack_name', models.CharField(max_length=150)),
                ('engineer', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('load_current_a', models.FloatField()),
                ('length_m', models.FloatField()),
                ('temperature_below_25', models.FloatField()),
                ('temperature_25_30', models.FloatField()),
                ('temperature_30_60', models.FloatField()),
                ('temperature_above_60', models.FloatField()),
                ('required_breaker_a', models.FloatField()),
                ('selected_breaker_a', models.FloatField()),
                ('recommended_cable_mm2', models.FloatField(blank=True, null=True)),
                ('worst_voltage_drop_v', models.FloatField(blank=True, null=True)),
                ('result_status', models.CharField(max_length=20)),
                ('calculation_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
